# VimFeatures.cmake — configure Vim's optional features and source dependencies.

set(WITH_FEATURES "huge" CACHE STRING "Vim feature level: tiny, normal, or huge")
set_property(CACHE WITH_FEATURES PROPERTY STRINGS tiny normal huge)
string(TOLOWER "${WITH_FEATURES}" XIM_FEATURE_LEVEL)
if(XIM_FEATURE_LEVEL STREQUAL "small")
    set(XIM_FEATURE_LEVEL tiny)
elseif(XIM_FEATURE_LEVEL STREQUAL "big")
    set(XIM_FEATURE_LEVEL normal)
endif()
if(NOT XIM_FEATURE_LEVEL MATCHES "^(tiny|normal|huge)$")
    message(FATAL_ERROR "WITH_FEATURES must be tiny, normal, or huge (got '${WITH_FEATURES}').")
endif()
set(WITH_FEATURES "${XIM_FEATURE_LEVEL}" CACHE STRING "Vim feature level: tiny, normal, or huge" FORCE)

set(WITH_GUI "auto" CACHE STRING "GUI backend: auto, none, gtk2, gtk3, gtk4, or motif")
set_property(CACHE WITH_GUI PROPERTY STRINGS auto none gtk2 gtk3 gtk4 motif)
string(TOLOWER "${WITH_GUI}" XIM_GUI_REQUESTED)
if(NOT XIM_GUI_REQUESTED MATCHES "^(auto|none|gtk2|gtk3|gtk4|motif)$")
    message(FATAL_ERROR "WITH_GUI must be auto, none, gtk2, gtk3, gtk4, or motif (got '${WITH_GUI}').")
endif()

option(WITH_AUTOSERVERNAME "Set the server name automatically at startup" OFF)
option(WITH_RIGHTLEFT "Include right-to-left language support" ON)
option(WITH_ARABIC "Include Arabic language support" ${WITH_RIGHTLEFT})

foreach(_xim_option IN ITEMS
        WITH_X11 WITH_WAYLAND WITH_PIXMAN WITH_CSCOPE WITH_CHANNEL
        WITH_NETBEANS WITH_TERMINAL WITH_IPV6 WITH_LUA WITH_MZSCHEME
        WITH_PERL WITH_PYTHON WITH_PYTHON3 WITH_RUBY WITH_TCL WITH_XIM)
    set(_xim_default auto)
    if(_xim_option MATCHES "^WITH_(LUA|MZSCHEME|PERL|PYTHON|PYTHON3|RUBY|TCL)$")
        # Autoconf enables language interpreters only when explicitly requested.
        set(_xim_default off)
    endif()
    set(${_xim_option} "${_xim_default}" CACHE STRING "Enable ${_xim_option} (auto, on, or off)")
    set_property(CACHE ${_xim_option} PROPERTY STRINGS auto on off)
    string(TOUPPER "${${_xim_option}}" _xim_value)
    if(NOT _xim_value MATCHES "^(AUTO|ON|OFF)$")
        message(FATAL_ERROR "${_xim_option} must be auto, on, or off (got '${${_xim_option}}').")
    endif()
    set(${_xim_option} "${_xim_value}" CACHE STRING "Enable ${_xim_option} (auto, on, or off)" FORCE)
endforeach()

function(xim_resolve_option option_name available description output_name)
    set(_xim_requested "${${option_name}}")
    set(_xim_available "${${available}}")
    if(_xim_requested STREQUAL "ON")
        if(NOT _xim_available)
            message(FATAL_ERROR "${option_name}=ON was requested, but ${description} is unavailable.")
        endif()
        set(_xim_enabled TRUE)
    elseif(_xim_requested STREQUAL "OFF")
        set(_xim_enabled FALSE)
    elseif(_xim_available)
        set(_xim_enabled TRUE)
    else()
        set(_xim_enabled FALSE)
    endif()
    set(${output_name} ${_xim_enabled} PARENT_SCOPE)
endfunction()

set(FEAT_TINY FALSE)
set(FEAT_NORMAL FALSE)
set(FEAT_HUGE FALSE)
if(XIM_FEATURE_LEVEL STREQUAL "tiny")
    set(FEAT_TINY TRUE)
elseif(XIM_FEATURE_LEVEL STREQUAL "normal")
    set(FEAT_NORMAL TRUE)
else()
    set(FEAT_HUGE TRUE)
endif()
xim_resolve_option(WITH_X11 XIM_HAVE_X11 "X11 development files" XIM_WITH_X11)
xim_resolve_option(WITH_PIXMAN XIM_HAVE_PIXMAN "pixman-1 development files" XIM_WITH_PIXMAN)

set(XIM_WITH_WAYLAND_AVAILABLE ${XIM_HAVE_WAYLAND})
if(FEAT_TINY)
    set(XIM_WITH_WAYLAND_AVAILABLE FALSE)
endif()
xim_resolve_option(WITH_WAYLAND XIM_WITH_WAYLAND_AVAILABLE
    "Wayland client library and wayland-scanner (Wayland is not available with tiny features)"
    XIM_WITH_WAYLAND)

set(XIM_CHANNEL_AVAILABLE ${XIM_HAVE_POSIX_CHANNELS})
if(FEAT_TINY)
    set(XIM_CHANNEL_AVAILABLE FALSE)
endif()
xim_resolve_option(WITH_CHANNEL XIM_CHANNEL_AVAILABLE
    "POSIX socket and name-resolution interfaces (channels are not available with tiny features)"
    XIM_WITH_CHANNEL)

set(XIM_IPV6_AVAILABLE ${XIM_HAVE_IPV6})
if(NOT XIM_WITH_CHANNEL)
    set(XIM_IPV6_AVAILABLE FALSE)
endif()
xim_resolve_option(WITH_IPV6 XIM_IPV6_AVAILABLE
    "IPv6 socket interfaces with channel support" XIM_WITH_IPV6)

set(XIM_NETBEANS_AVAILABLE ${XIM_WITH_CHANNEL})
if(FEAT_TINY)
    set(XIM_NETBEANS_AVAILABLE FALSE)
endif()
xim_resolve_option(WITH_NETBEANS XIM_NETBEANS_AVAILABLE
    "NetBeans integration requirements (evaluation and channels)" XIM_WITH_NETBEANS)

set(XIM_TERMINAL_AVAILABLE FALSE)
if(FEAT_HUGE AND XIM_WITH_CHANNEL)
    set(XIM_TERMINAL_AVAILABLE TRUE)
endif()
xim_resolve_option(WITH_TERMINAL XIM_TERMINAL_AVAILABLE
    "terminal emulator requirements (huge features and channels)" XIM_WITH_TERMINAL)

set(XIM_CSCOPE_AVAILABLE FALSE)
if(UNIX AND FEAT_HUGE)
    set(XIM_CSCOPE_AVAILABLE TRUE)
endif()
xim_resolve_option(WITH_CSCOPE XIM_CSCOPE_AVAILABLE
    "Cscope support on Unix with huge features" XIM_WITH_CSCOPE)

set(XIM_GUI_BACKEND none)
if(XIM_GUI_REQUESTED STREQUAL "auto")
    if(XIM_GTK3_FOUND AND XIM_WITH_X11)
        set(XIM_GUI_BACKEND gtk3)
    elseif(XIM_GTK4_FOUND)
        set(XIM_GUI_BACKEND gtk4)
    elseif(XIM_GTK2_FOUND AND XIM_WITH_X11)
        set(XIM_GUI_BACKEND gtk2)
    elseif(XIM_HAVE_MOTIF)
        set(XIM_GUI_BACKEND motif)
    endif()
elseif(NOT XIM_GUI_REQUESTED STREQUAL "none")
    set(XIM_GUI_BACKEND "${XIM_GUI_REQUESTED}")
    if(XIM_GUI_BACKEND STREQUAL "gtk2" AND NOT (XIM_GTK2_FOUND AND XIM_WITH_X11))
        message(FATAL_ERROR "WITH_GUI=gtk2 requires GTK 2 development files and X11.")
    elseif(XIM_GUI_BACKEND STREQUAL "gtk3" AND NOT (XIM_GTK3_FOUND AND XIM_WITH_X11))
        message(FATAL_ERROR "WITH_GUI=gtk3 requires GTK 3 development files and X11.")
    elseif(XIM_GUI_BACKEND STREQUAL "gtk4" AND NOT XIM_GTK4_FOUND)
        message(FATAL_ERROR "WITH_GUI=gtk4 requires GTK 4.10 or later development files.")
    elseif(XIM_GUI_BACKEND STREQUAL "motif" AND NOT XIM_HAVE_MOTIF)
        message(FATAL_ERROR "WITH_GUI=motif requires Motif and X11 development files.")
    endif()
endif()

set(FEAT_GUI_GTK FALSE)
set(FEAT_GUI_MOTIF FALSE)
set(USE_GTK3 FALSE)
set(USE_GTK4 FALSE)
if(XIM_GUI_BACKEND MATCHES "^gtk")
    set(FEAT_GUI_GTK TRUE)
endif()
if(XIM_GUI_BACKEND STREQUAL "motif")
    set(FEAT_GUI_MOTIF TRUE)
endif()
if(XIM_GUI_BACKEND STREQUAL "gtk3")
    set(USE_GTK3 TRUE)
elseif(XIM_GUI_BACKEND STREQUAL "gtk4")
    set(USE_GTK4 TRUE)
endif()

set(XIM_XIM_AVAILABLE FALSE)
if(NOT XIM_GUI_BACKEND STREQUAL "none")
    set(XIM_XIM_AVAILABLE TRUE)
endif()
xim_resolve_option(WITH_XIM XIM_XIM_AVAILABLE
    "GUI input method support (a GUI backend must be selected)" XIM_WITH_XIM)

if(NOT WITH_RIGHTLEFT AND WITH_ARABIC)
    message(FATAL_ERROR "WITH_ARABIC=ON requires WITH_RIGHTLEFT=ON.")
endif()
set(DISABLE_RIGHTLEFT FALSE)
set(DISABLE_ARABIC FALSE)
if(NOT WITH_RIGHTLEFT)
    set(DISABLE_RIGHTLEFT TRUE)
endif()
if(NOT WITH_ARABIC)
    set(DISABLE_ARABIC TRUE)
endif()

foreach(_xim_interpreter IN ITEMS LUA MZSCHEME PERL PYTHON PYTHON3 RUBY TCL)
    set(_xim_available_var XIM_HAVE_${_xim_interpreter})
    set(_xim_available ${${_xim_available_var}})
    if(FEAT_TINY)
        set(_xim_available FALSE)
    endif()
    set(_xim_option WITH_${_xim_interpreter})
    set(_xim_resolved XIM_WITH_${_xim_interpreter})
    xim_resolve_option(${_xim_option} _xim_available
        "${_xim_interpreter} development files (and non-tiny features)" ${_xim_resolved})
    set(FEAT_${_xim_interpreter} ${${_xim_resolved}})
endforeach()

set(ENABLE_CSCOPE ${XIM_WITH_CSCOPE})
set(FEAT_IPV6 ${XIM_WITH_IPV6})
set(FEAT_NETBEANS_INTG ${XIM_WITH_NETBEANS})
set(FEAT_JOB_CHANNEL ${XIM_WITH_CHANNEL})
set(FEAT_TERMINAL ${XIM_WITH_TERMINAL})
set(FEAT_AUTOSERVERNAME ${WITH_AUTOSERVERNAME})
set(FEAT_XIM ${XIM_WITH_XIM})
set(HAVE_X11 ${XIM_WITH_X11})
set(HAVE_WAYLAND ${XIM_WITH_WAYLAND})
set(HAVE_PIXMAN ${XIM_WITH_PIXMAN})

message(STATUS "Vim features: ${XIM_FEATURE_LEVEL}")
message(STATUS "GUI backend: ${XIM_GUI_BACKEND}")
message(STATUS "Optional features: X11=${XIM_WITH_X11}, Wayland=${XIM_WITH_WAYLAND}, pixman=${XIM_WITH_PIXMAN}, channels=${XIM_WITH_CHANNEL}, terminal=${XIM_WITH_TERMINAL}")
message(STATUS "Interpreters: Lua=${XIM_WITH_LUA}, Perl=${XIM_WITH_PERL}, Python=${XIM_WITH_PYTHON}, Python3=${XIM_WITH_PYTHON3}, Ruby=${XIM_WITH_RUBY}, Tcl=${XIM_WITH_TCL}")
