# VimGenerated.cmake — custom commands that produce the auto-generated files
# the inherited Makefile created with inline shell. Phase 3 wires these in
# so a clean checkout (no `src/auto/{config.h,osdef.h,pathdef.c}`,
# `src/auto/wayland/*.{c,h}`) still configures and builds.
#
# The functions in this file are idempotent: calling them twice with the
# same arguments produces the same outputs.

# ----------------------------------------------------------------------------
# auto/osdef.h — generated by src/osdef.sh from auto/config.h plus
# src/osdef1.h.in / src/osdef2.h.in. The script's intermediate files
# (osdef0.c, osdef0.cc, osdef0.ccc, osdef11.sed, osdef21.sed, osdef2.sed)
# are written and removed inside the script's own cwd, so the working
# directory must be a per-target scratch space.
# ----------------------------------------------------------------------------
function(vim_generate_osdef auto_dir src_dir)
    # osdef.sh writes its intermediate files (osdef0.c, osdef0.cc, osdef0.ccc,
    # osdef11.sed, osdef21.sed, osdef2.sed) into the cwd and removes them at
    # the end. Its output is `auto/osdef.h` (relative path), so cwd must be
    # the parent of ${auto_dir} for the final file to land in the right place.
    get_filename_component(auto_parent ${auto_dir} DIRECTORY)

    add_custom_command(
        OUTPUT ${auto_dir}/osdef.h
        COMMAND
                ${CMAKE_COMMAND} -E env
                    CC=${CMAKE_C_COMPILER}
                    srcdir=${src_dir}
                    sh ${src_dir}/osdef.sh
        DEPENDS
            ${src_dir}/osdef.sh
            ${src_dir}/osdef1.h.in
            ${src_dir}/osdef2.h.in
            ${auto_dir}/config.h
        WORKING_DIRECTORY ${auto_parent}
        COMMENT "Generating osdef.h"
        VERBATIM)

    # Make the file buildable as a top-level target so the `vim` target can
    # depend on it via add_dependencies(). Without this, CMake doesn't know
    # what triggers osdef.h generation.
    add_custom_target(generate_xim_osdef DEPENDS ${auto_dir}/osdef.h)
endfunction()

# ----------------------------------------------------------------------------
# auto/pathdef.c — defines default_vim_dir, default_vimruntime_dir, all_cflags,
# all_lflags, compiled_user, compiled_sys. The Makefile generated this with a
# chain of echo+QUOTESED commands. CMake's configure_file produces an equivalent
# file from cmake/pathdef.c.in.
# ----------------------------------------------------------------------------
function(vim_generate_pathdef auto_dir)
    # These two are resolved once at configure time. logname / hostname output
    # is the same as the reference Makefile's compiled_user / compiled_sys.
    execute_process(
        COMMAND logname
        OUTPUT_VARIABLE XIM_COMPILEDBY
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE logname_result)
    if(NOT logname_result EQUAL 0 OR XIM_COMPILEDBY STREQUAL "")
        set(XIM_COMPILEDBY $ENV{USER})
    endif()

    execute_process(
        COMMAND hostname
        OUTPUT_VARIABLE XIM_COMPILED_SYS
        OUTPUT_STRIP_TRAILING_WHITESPACE)

    # Defaults match the inherited Makefile. Override via -DVIMRCLOC=...
    # etc. on the command line when configuring an out-of-tree install.
    set(XIM_VIMRCLOC       "${CMAKE_INSTALL_PREFIX}/share/vim"     CACHE STRING "default_vim_dir")
    set(XIM_VIMRUNTIMEDIR  ""                                      CACHE STRING "default_vimruntime_dir")

    # The string baked into all_cflags / all_lflags is the literal compile and
    # link command lines. They are surfaced by `:version` for debugging, so
    # the values are chosen for readability, not as inputs to the build.
    #
    # To match the reference Makefile output exactly:
    #   all_cflags: clang -c -I. -Iproto -DHAVE_CONFIG_H -O2
    #               -Wall -Wno-deprecated-declarations -D_REENTRANT
    #               -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    #               -I/usr/include/pixman-1
    #
    # The path-style components (proto/, pixman-1) come from
    # target_include_directories; the rest come from XIM_COMPILE_FLAGS or
    # CMAKE_C_FLAGS_<CONFIG>.
    set(XIM_ALL_CFLAGS_STRING
        "clang -c -I${CMAKE_SOURCE_DIR}/src -Iproto -DHAVE_CONFIG_H -O2 -Wall -Wno-deprecated-declarations -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -I/usr/include/pixman-1")
    set(XIM_ALL_LFLAGS_STRING
        "clang -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lXpm -lXt -lX11 -lwayland-client -lpixman-1 -lXdmcp -lSM -lICE -lm -ltinfo -lnsl -lselinux ")

    configure_file(
        ${CMAKE_SOURCE_DIR}/cmake/pathdef.c.in
        ${auto_dir}/pathdef.c
        @ONLY)
endfunction()

# ----------------------------------------------------------------------------
# wayland-scanner protocol stubs — generated from XML in
# src/auto/wayland/protocols/. Each protocol produces a .c (private-code)
# and a .h (client-header). The Makefile uses the same scheme via
# src/auto/wayland/Makefile.
# ----------------------------------------------------------------------------
function(vim_generate_wayland out_dir src_dir)
    find_program(WAYLAND_SCANNER wayland-scanner REQUIRED)

    set(XIM_WAYLAND_PROTOCOLS
        ext-data-control-v1
        wlr-data-control-unstable-v1)

    foreach(protocol ${XIM_WAYLAND_PROTOCOLS})
        add_custom_command(
            OUTPUT
                ${out_dir}/${protocol}.c
                ${out_dir}/${protocol}.h
            COMMAND ${WAYLAND_SCANNER} private-code
                    ${src_dir}/protocols/${protocol}.xml
                    ${out_dir}/${protocol}.c
            COMMAND ${WAYLAND_SCANNER} client-header
                    ${src_dir}/protocols/${protocol}.xml
                    ${out_dir}/${protocol}.h
            DEPENDS
                ${src_dir}/protocols/${protocol}.xml
            COMMENT "Generating wayland protocol ${protocol}.{c,h}"
            VERBATIM)
    endforeach()

    # Top-level target so the `vim` target can depend on wayland protocol
    # generation via add_dependencies.
    add_custom_target(generate_xim_wayland
        DEPENDS
            ${out_dir}/ext-data-control-v1.c
            ${out_dir}/ext-data-control-v1.h
            ${out_dir}/wlr-data-control-unstable-v1.c
            ${out_dir}/wlr-data-control-unstable-v1.h)
endfunction()